language: python
jobs:
  fast_finish: true
  include:
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2 # Python 3.7.4 running on macOS 10.14.4
      language: shell # 'language: python' is an error on Travis CI macOS
      before_install:
        - brew install --cask mactex
        - brew install gettext
        - brew link gettext --force
    - name: "Python 3.8.0 on Windows"
      os: windows # Windows 10.0.17134 N/A Build 17134
      language: shell # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - choco install miktex.portable
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
  allow_failures:
    - name: "Python 3.8.0 on Windows"
      os: windows # Windows 10.0.17134 N/A Build 17134
      language: shell # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - choco install miktex.portable
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip3 install --editable ".[dev]"
script:
  - python3 manage.py test
after_success:
  - coverage run --source=survey --omit=survey/migrations/* ./manage.py test
  - coverage html
  - coveralls
